### ISSUE TITLE
Release the pretrained model of the Generalization NeRF

### ISSUE THREAD

**Issue by Mobiuslqm** [autonomousvision/factor-fields#10]
Hi! Anpei !  your work and idea are really wonderful. Could you please release the pretrained model of google  3d object datasets?

**Comment by apchenstu** [comment]
[google-obj-mlpC.zip](https://github.com/autonomousvision/factor-fields/files/12505375/google-obj-mlpC.zip)
Hi there, thanks! here is the checkpoint file and its log file

**Comment by Mobiuslqm** [comment]
Thanks for your quickly reply!
