### ISSUE TITLE
How to overfit 4-D data?

### ISSUE THREAD

**Issue by eugenelyj** [autonomousvision/factor-fields#12]
Dear authors, thanks for sharing the awesome code!

I want to know how to overfit 4-D data, for example, (x,y,i,j)?

Which mode should I choose, or how to modify?

**Comment by apchenstu** [comment]
Hi eugenelyj, the model does not support 4D data. While I'm unsure about the specifics of the job you are working on, I would suggest starting with the image fitting and SDF reconstruction models if your work does not target radiance field reconstruction.

**Comment by eugenelyj** [comment]
Thanks for the reply. I am fitting (x,y,t1,t2) where (x,y) are pixel coordinates and (t1,t2) are timestamps. I find it also works to use the factor field (with config of fitting image) to map (x,y) and (t1,t2) into features separately, then use a simple MLP like what is used in the factor field to map the concat features into the final value.

However, the parameters in the config are a bit complex to read. I think the most important parameters for me are:
```
  basis_dims: [32,32,32,16,16,16]
  basis_resos: [32,51,70,89,108,128]
  freq_bands: [2. , 3.2, 4.4, 5.6, 6.8, 8.]
```
If i want to increase the resolution and complexity to fit some high-frequency details, how to change the parameters?
