### ISSUE TITLE
Unused freq_bands in 2d regression

### ISSUE THREAD

**Issue by salykova** [autonomousvision/factor-fields#14]
@apchenstu

In 2d regression `freq_bands` are specified in `image.yaml` 
https://github.com/autonomousvision/factor-fields/blob/67010a4fefe2ed0b1424a8b71ada4e4324a77269/configs/image.yaml#L13
but not used due to this LOC
https://github.com/autonomousvision/factor-fields/blob/67010a4fefe2ed0b1424a8b71ada4e4324a77269/models/FactorFields.py#L277
May I kindly ask you why we need to redefine `freq_bands`?

**Comment by apchenstu** [comment]
Hi Salykova, this is because the bounding box (width and height) of the images can vary, unlike other signals such as SDF or NeRF, where it is fixed. Therefore, we adjust its frequency accordingly for the image.

**Comment by salykova** [comment]
@apchenstu  thanks for your reply!
