### ISSUE TITLE
Problem with sdf regression dataset

### ISSUE THREAD

**Issue by AbdelazizBouzidi** [autonomousvision/factor-fields#15]
Hello, 

The one drive linke your provide regarding the pre-calculated sdf fields is not working. 
Can you please provide a new link, or at least specifie the strategy used to sample the 8 millions querry points used for training. 

thank you in advance.

**Comment by apchenstu** [comment]
Sorry for the misleading, the links are updated now, please try again.

**Comment by AbdelazizBouzidi** [comment]
Amazing, Thanks a lot.
