### ISSUE TITLE
Reproducing nerf generalization experiments

### ISSUE THREAD

**Issue by TangYucopper** [autonomousvision/factor-fields#7]
Hi there, thanks for your amazing codes!
I'm trying to reproduce the nerf generalization experiments, for which I run 

> python train_across_scene.py configs/nerf_set.yaml

, followed by changing the `ckpt` in `nerf_ft.yaml` to the pretrained checkpoint obtained in the first stage, setting `with_dropout` in `nerf_ft.yaml` as False, setting `basis_type` as `'mlp'` and running:

> python train_across_scene_ft.py configs/nerf_ft.yaml

However, the results reported by the latter are 21.84 PSNR, which is worse than that reported in your paper. I wonder if my reproducing procedure is correct. And I would appreciate it if I can get your valuable guidance.

Thanks.

**Comment by apchenstu** [comment]
Hi there, which scene and which setting (how many views) are you working on?

**Comment by TangYucopper** [comment]
Hi, I am working on scene 100, as it is the default in nerf_ft.yaml. And the factor field was pretrained on scene [0, 100)

**Comment by apchenstu** [comment]
> Hi, I am working on scene 100, as it is the default in nerf_ft.yaml. And the factor field was pre-trained on scene [0, 100)

Okay, how many views? here are the training and testing script: https://github.com/autonomousvision/factor-fields/blob/main/run_batch.py#L52-L84

the scores are an average score of 8 random sample scenes.

**Comment by TangYucopper** [comment]
250 views. Thank you for your reply. I will give it a try.
